### ISSUE TITLE
Empty data frame encountered during demo run with epistasis.test.csv

### ISSUE THREAD

**Issue by ducryf** [jlevy44/InteractionTransformer#2]
Hi,

when running the demo file on python I encountered an error in line "transformer.fit(X_train,y_train)". I uncommented the lines 204, 205, and 208 [here ](https://github.com/jlevy44/InteractionTransformer/blob/b751e2ab63122c2e7ee9d9e6733f01d9d0b1829f/interactiontransformer/InteractionTransformer.py#L204). The array in shap_test.pkl contains only nan. The output of python and the error message is below:

Shap Interaction Size: (240, 56, 56)
Empty DataFrame
Columns: [feature_1, feature_2, shap_interaction_score]
Index: []
<pandas.core.indexing._iLocIndexer object at 0x2abb2b457770>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/ducryf/int/interactiontransformer/InteractionTransformer.py", line 209, in fit
    self.design_terms='+'.join((np.core.defchararray.add(np.vectorize(lambda x: "Q('{}')*".format(x))(true_top_interactions.iloc[:,0]),np.vectorize(lambda x: "Q('{}')".format(x))(true_top_interactions.iloc[:,1]))).tolist())
  File "/usr/scratch/blauen/ducryf/miniconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2091, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/usr/scratch/blauen/ducryf/miniconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2161, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/usr/scratch/blauen/ducryf/miniconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2117, in _get_ufunc_and_otypes
    raise ValueError('cannot call `vectorize` on size 0 inputs '
ValueError: cannot call `vectorize` on size 0 inputs unless `otypes` is set

I get the same error on two systems, one using WSL (windows subsystem for linux) with Ubuntu 20.04, anaconda 4.9.2, and python 3.8.5. The other system is CentOS 7.4.1708, miniconda 4.9.2, and python 3.7.4.

How can I solve this issue?

Cheers,
Fabian

**Comment by jlevy44** [comment]
Hi @ducryf, I will try to debug. What happens if you set dask_interactions to False ?

**Comment by ducryf** [comment]
Thanks for the help @jlevy44 
If I set [daks_interactions](https://github.com/jlevy44/InteractionTransformer/blob/b751e2ab63122c2e7ee9d9e6733f01d9d0b1829f/interactiontransformer/InteractionTransformer.py#L137) to false the following happens:

>>> transformer.fit(X_train,y_train)
Shap Interaction Size: (2, 56, 56)
Empty DataFrame
Columns: [feature_1, feature_2, shap_interaction_score]
Index: []
Traceback (most recent call last):
...
ValueError: cannot call `vectorize` on size 0 inputs unless `otypes` is set
>>>

Shap Interaction Size: (2, 56, 56) changes from 240 to 2, but the error (and traceback) remains the same.

**Comment by jlevy44** [comment]
Ok, and you had installed the latest build of the transformer?

**Comment by jlevy44** [comment]
I just ran it on my machine and it appeared to work

**Comment by jlevy44** [comment]
Can you try reinstalling from github? I made a few small changes. Some of the issues could be related to upgraded dependencies that I did not enforce enough restrictions on.

```
pip install git+https://github.com/jlevy44/InteractionTransformer --upgrade
```

**Comment by ducryf** [comment]
That last commit did it. Now it runs flawlessly, thanks a lot!
