### ISSUE TITLE
Possibilities InteractionTransfomer in combination with Neural Network

### ISSUE THREAD

**Issue by jvdboogaard** [jlevy44/InteractionTransformer#4]
Dear jlevy44,

Once again I want to thank you for being able to use your code.

I have used the code for both XGBoost and Random Forest. Now I would like to use the code in combination with Neural Network. I know that I can't use TreeExplainer for the SHAP values but I can use KernelExplainer for the SHAP values. But there is no attribute 'shap_interaction_values' for this Explainer. Do you have any suggestions on how to implement this/make it possible to use the code for NN?

Thanks in advance.

Kind regards,
Jeroen

**Comment by jlevy44** [comment]
Hi @jvdboogaard , that is a great idea and certainly something we may incorporate. Here's a few papers that discuss such methods. 
https://openreview.net/forum?id=BkgnhTEtDS
https://openreview.net/forum?id=ByOfBggRZ
Currently, we do not offer approaches that are amenable to neural networks. Feel free to open a PR if you find something interesting!
